version: '3'

services:
  api:
    build: 
      context: ../
      dockerfile: docker/Dockerfile 
      args:
        port: ${PORT}
    env_file:
      - ../.env
    ports:
      - "${PORT}:${PORT}"
    depends_on: 
      - database
  database:
    image: mongo:4.0
    restart: always
    env_file:
      - ../.env
    expose:
      - 27017
    volumes:
      - document-data:/data/db
    command: "mongod --logpath=${MONGO_LOG_FILE}"

volumes:
  document-data:

    