
version: '3'
services:
  api:
    build: 
      context: ../
      dockerfile: docker/Dockerfile.test
      args:
        port: ${PORT}
    env_file:
      - ../.env
    ports:
      - "${PORT}:${PORT}"
    depends_on: 
      - database
  database:
    image: mongo:4.0
    env_file:
      - ../.env
    expose:
      - 27017
    command: "mongod --logpath=${MONGO_LOG_FILE}"