
version: '3'
services:
  backend-test:
    build: 
      context: ../
      dockerfile: docker/Dockerfile.test
      args:
        port: ${PORT}
    env_file:
      - ../.env
    ports:
      - "${PORT}:${PORT}"
    environment:
      WAIT_HOSTS: database:27017
    networks:
      - backend
  database:
    image: mongo:4.0
    env_file:
      - ../.env
    expose:
      - 27017
    networks:
      - backend
    command: "mongod --smallfiles --logpath=${MONGO_LOG_FILE}"
    
networks:
  backend: